FROM alpine:3.8

LABEL name="alpine JDK8"

ENV java_down_url='https://repo.huaweicloud.com/java/jdk/8u181-b13/jdk-8u181-linux-x64.tar.gz'

RUN apk --no-cache add curl \
    && echo Downloading jdk-8u181-linux-x64.tar.gz... \
    && curl -L -o /tmp/jdk.tar.gz ${java_down_url} \
    && mkdir /opt/{java,jar} \
    && tar zxf /tmp/jdk.tar.gz --strip-components 1 -C /opt/java \
    && rm -rf /tmp/jdk.tar.gz \
    && rm -rf /etc/localtime && ln -sfn /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && rm -rf /opt/java/src.zip \
    && rm -rf /opt/java/javafx-src.zip

#JAVA_OPTS
ENV JAVA_HOME=/opt/java \
    PATH=/opt/java/bin:$PATH \
    JAVA_OPTS="-Xms1024m \
    -Xmx1024m \
    -Xmn384m \
    -Xss512k \
    -XX:SurvivorRatio=10 \
    -XX:MetaspaceSize=128m \
    -XX:MaxMetaspaceSize=196m \
    -XX:+UseConcMarkSweepGC \
    -XX:+CMSScavengeBeforeRemark \
    -XX:+CMSParallelRemarkEnabled \
    -XX:+AggressiveOpts"

WORKDIR /opt/jar
