FROM rootww/alpine-glibc:3.9-2.29

LABEL name="alpine JDK8"

ENV java_down_url='http://repo.huaweicloud.com/java/jdk/8u181-b13/jdk-8u181-linux-x64.tar.gz'

RUN echo Downloading jdk-8u181-linux-x64.tar.gz... \
    && wget -q -O /tmp/jdk.tar.gz ${java_down_url} \
    && mkdir -p /opt/java /opt/jar \
    && tar zxf /tmp/jdk.tar.gz --strip-components 1 -C /opt/java \
    && rm -rf /tmp/jdk.tar.gz \
    && rm -rf /etc/localtime && ln -sfn /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && rm -rf /opt/java/src.zip \
              /opt/java/javafx-src.zip \
              /opt/jdk/jre/plugin \
              /opt/jdk/jre/bin/javaws \
              /opt/jdk/jre/bin/orbd \
              /opt/jdk/jre/bin/pack200 \
              /opt/jdk/jre/bin/policytool \
              /opt/jdk/jre/bin/rmid \
              /opt/jdk/jre/bin/rmiregistry \
              /opt/jdk/jre/bin/servertool \
              /opt/jdk/jre/bin/tnameserv \
              /opt/jdk/jre/bin/unpack200 \
              /opt/jdk/jre/lib/javaws.jar \
              /opt/jdk/jre/lib/deploy* \
              /opt/jdk/jre/lib/desktop \
              /opt/jdk/jre/lib/*javafx* \
              /opt/jdk/jre/lib/*jfx* \
              /opt/jdk/jre/lib/amd64/libdecora_sse.so \
              /opt/jdk/jre/lib/amd64/libprism_*.so \
              /opt/jdk/jre/lib/amd64/libfxplugins.so \
              /opt/jdk/jre/lib/amd64/libglass.so \
              /opt/jdk/jre/lib/amd64/libgstreamer-lite.so \
              /opt/jdk/jre/lib/amd64/libjavafx*.so \
              /opt/jdk/jre/lib/amd64/libjfx*.so \
              /opt/jdk/jre/lib/ext/jfxrt.jar \
              /opt/jdk/jre/lib/oblique-fonts \
              /opt/jdk/jre/lib/plugin.jar

#JAVA_OPTS
ENV JAVA_HOME=/opt/java \
    PATH=/opt/java/bin:$PATH \
    JAVA_OPTS="-Xms1024m \
    -Xmx1024m \
    -Xmn384m \
    -Xss512k \
    -XX:SurvivorRatio=10 \
    -XX:MetaspaceSize=128m \
    -XX:MaxMetaspaceSize=196m \
    -XX:+UseConcMarkSweepGC \
    -XX:+CMSScavengeBeforeRemark \
    -XX:+CMSParallelRemarkEnabled \
    -XX:+AggressiveOpts"

WORKDIR /opt/jar
